# Generated by Django 5.0.1 on 2024-06-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('retailer_name', models.CharField(default=True, max_length=100)),
            ],
            options={
                'db_table': 'Product_Table',
            },
        ),
    ]
